# Generated by Django 3.1.7 on 2021-04-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('title', models.TextField(max_length=100, verbose_name='')),
                ('author', models.TextField(max_length=100, verbose_name='')),
                ('narrator', models.TextField(max_length=100, verbose_name='')),
                ('file', models.FileField(upload_to='', verbose_name='')),
                ('duration', models.DurationField(verbose_name='')),
                ('timeupload', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('name', models.TextField(max_length=100, verbose_name='')),
                ('file', models.FileField(upload_to='', verbose_name='')),
                ('duration', models.DurationField(verbose_name='')),
                ('host', models.TextField(max_length=100, verbose_name='')),
                ('participants', models.CharField(max_length=50, verbose_name='')),
                ('timeupload', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('name', models.TextField(max_length=100, verbose_name='')),
                ('file', models.FileField(upload_to='')),
                ('duration', models.DurationField(verbose_name='')),
                ('timeupload', models.DateTimeField(verbose_name='')),
            ],
        ),
    ]
