# Generated by Django 3.1.7 on 2021-04-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(default='audiobook', editable=False)),
                ('title', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=100)),
                ('narrator', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to='audiobooks')),
                ('duration', models.CharField(max_length=50)),
                ('timeupload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(default='podcast', editable=False)),
                ('name', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to='podcasts')),
                ('duration', models.CharField(max_length=50)),
                ('host', models.TextField(max_length=100)),
                ('participants', models.CharField(max_length=1010)),
                ('timeupload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(default='song', editable=False)),
                ('name', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to='songs')),
                ('duration', models.CharField(max_length=50)),
                ('timeupload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
