# Generated by Django 3.1.7 on 2021-04-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='author',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='narrator',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='timeupload',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='host',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='timeupload',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='timeupload',
            field=models.DateTimeField(),
        ),
    ]
