# Generated by Django 3.1.7 on 2021-04-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0002_auto_20210414_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='timeupload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='timeupload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='timeupload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
