# Generated by Django 3.1.7 on 2021-04-14 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0003_auto_20210414_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='dateupload',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='timeupload',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
