# Generated by Django 3.1.7 on 2021-04-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0004_auto_20210414_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='dateupload',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='timeupload',
            field=models.TimeField(),
        ),
    ]
