# Generated by Django 3.1.7 on 2021-04-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0005_auto_20210414_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='dateupload',
            field=models.DateField(auto_now_add=True),
        ),
    ]
