# Generated by Django 3.1.7 on 2021-04-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0006_auto_20210414_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='file',
            field=models.FileField(upload_to='static/audiobooks'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to='static/podcasts'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='static/songs'),
        ),
    ]
