# Generated by Django 3.1.7 on 2021-04-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0009_auto_20210416_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='file',
            field=models.FileField(upload_to='audiobooks'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to='podcasts'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='songs'),
        ),
    ]
