# Generated by Django 3.1.7 on 2021-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0010_auto_20210417_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='type',
            field=models.TextField(default='audiobook', editable=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='type',
            field=models.TextField(default='podcast', editable=False),
        ),
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.TextField(default='song', editable=False),
        ),
    ]
