# Generated by Django 3.1.7 on 2021-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0011_auto_20210417_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.CharField(max_length=500),
        ),
    ]
