# Generated by Django 3.1.7 on 2021-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioServer', '0012_auto_20210417_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.CharField(max_length=1010),
        ),
    ]
